// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-OwuhtX8cNYCGhFB9f5j5HCoNp12xpm0',
    appId: '1:33305405962:web:74eb5534c69ede59e44df3',
    messagingSenderId: '33305405962',
    projectId: 'palmnazi-5259e',
    authDomain: 'palmnazi-5259e.firebaseapp.com',
    storageBucket: 'palmnazi-5259e.firebasestorage.app',
    measurementId: 'G-7G1Q956CZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5dOjXYINqljIqxbzpEkI-u2aCPS3xO9Q',
    appId: '1:33305405962:android:dbdef18d301931cce44df3',
    messagingSenderId: '33305405962',
    projectId: 'palmnazi-5259e',
    storageBucket: 'palmnazi-5259e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQ2qzZI08R_PirWqoiILIkjOjEwo6M-8',
    appId: '1:33305405962:ios:34c216e012a466aee44df3',
    messagingSenderId: '33305405962',
    projectId: 'palmnazi-5259e',
    storageBucket: 'palmnazi-5259e.firebasestorage.app',
    iosBundleId: 'com.example.palmnazi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmQ2qzZI08R_PirWqoiILIkjOjEwo6M-8',
    appId: '1:33305405962:ios:34c216e012a466aee44df3',
    messagingSenderId: '33305405962',
    projectId: 'palmnazi-5259e',
    storageBucket: 'palmnazi-5259e.firebasestorage.app',
    iosBundleId: 'com.example.palmnazi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-OwuhtX8cNYCGhFB9f5j5HCoNp12xpm0',
    appId: '1:33305405962:web:43892855cd598b68e44df3',
    messagingSenderId: '33305405962',
    projectId: 'palmnazi-5259e',
    authDomain: 'palmnazi-5259e.firebaseapp.com',
    storageBucket: 'palmnazi-5259e.firebasestorage.app',
    measurementId: 'G-PZTSPT29CM',
  );
}
